# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
    - 'gh-disabled-workflows/**'
    - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
    - 'gh-disabled-workflows/**'
    - '*.md'

jobs:
  linux_and_coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Workflow dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install flake8 flake8-import-order pytest coverage
        
    - name: Install project dependencies
      run: |
        pip install .[test]
      
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: graphviz for visualization test
      run: |
        sudo apt-get update && sudo apt-get install -yq graphviz
        
    - name: Test with coverage & pytest
      run: |
        coverage run --source=tdvisu -m pytest .
        coverage xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests

  other_os_tests:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Workflow dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        
    - name: Install project dependencies
      run: |
        pip install .[test]

    - name: Download graphviz To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: https://www2.graphviz.org/Packages/stable/portable_source/graphviz-2.44.1.tar.gz
        # New filename to rename the downloaded file
        #file-name: # optional
        # Path to download the file
        #location:  optional, default is .
    
    - name: install graphviz for visualization test
      # windows install
      run: |
        tar xzvf graphviz-2.44.1.tar.gz
        cd graphviz-2.44.1
        ./configure
        make
        make install
        
    - name: Test with pytest
      run: |
        # Tests reside in folder 'test'
        pytest .\test
    
