# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
    - 'gh-disabled-workflows/**'
    - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
    - 'gh-disabled-workflows/**'
    - '*.md'

jobs:
  linux_and_coverage:
    if: failure()
    runs-on: ubuntu-latest

    steps:

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Workflow dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install flake8 flake8-import-order pytest coverage

    - name: Install project dependencies
      run: |
        pip install .[test]

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: graphviz for visualization test
      run: |
        sudo apt-get update && sudo apt-get install -yq graphviz

    - name: Test with coverage & pytest
      run: |
        coverage run --source=tdvisu -m pytest .
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests

  other_os_tests:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.3
      with:
        # Whether to activate the conda base env (Default: 'true')
        activate-conda: true
        # If conda should be updated before running other commands (Default: 'false')
        update-conda: true
        # Python version which should be installed with conda (default: 'Default')
        python-version: 3.8

    - name: Install Workflow dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Install project dependencies
      run: |
        pip install .[test]
    
    - name: Install GNU Triangulated Surface Library
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install gts
      

    - name: install graphviz for visualization test
      run: |
        conda install -c anaconda graphviz

    - name: add graphviz PATH
      run: |
        # should give base conda python
        $python=Get-Command python | select -Property Source
        $pypath=Split-Path $python.Source -Parent

        # Add to PATH, we know pypath is on it
        $dot=[IO.Path]::Combine($pypath, 'Library', 'bin', 'graphviz')
        echo "::add-path::$dot"
      shell: powershell

    - name: register plugins for graphviz
      run: |
        # execute dot
        dot -V
        dot -c

    - name: Test with pytest
      run: |
        # Tests reside in folder 'test'
        pytest ./test
